USE RA1800378

CREATE TABLE Usuario
(
ID INT PRIMARY KEY IDENTITY, 
Login VARCHAR(30) UNIQUE NOT NULL,
Senha INT NOT NULL, 
DtExpiracao DATE DEFAULT('01/01/1900') NOT NULL  
);

CREATE TABLE Coordenador
(
ID INT PRIMARY KEY IDENTITY,
Id_usuario INT NOT NULL,
Nome VARCHAR(40) NOT NULL,
Email VARCHAR(50) UNIQUE NOT NULL,
Celular VARCHAR(11) UNIQUE NOT NULL
CONSTRAINT FK_ID_USUARIO FOREIGN KEY (Id_usuario) REFERENCES Usuario(ID)
);

CREATE TABLE Aluno
(
ID INT PRIMARY KEY IDENTITY,
Id_usuario INT NOT NULL,
Nome VARCHAR(40) NOT NULL,
Email VARCHAR(50) UNIQUE NOT NULL,
Celular VARCHAR(11) UNIQUE NOT NULL,
RA INT NOT NULL,
FOTO VARCHAR(100)
CONSTRAINT FK_ID_USUARIOALUNO FOREIGN KEY (Id_usuario) REFERENCES Usuario(ID)
);

CREATE TABLE Professor
(
ID INT PRIMARY KEY IDENTITY,
Id_Usuario INT NOT NULL,
Email VARCHAR(50) UNIQUE NOT NULL,
Celular VARCHAR(11) UNIQUE NOT NULL,
Apelido VARCHAR(15) NOT NULL
CONSTRAINT FK_ID_USUARIOPROFESSOR FOREIGN KEY (Id_usuario) REFERENCES Usuario(ID)
);

CREATE TABLE DISCIPLINA
(
	ID SMALLINT PRIMARY KEY IDENTITY,
	NOME VARCHAR (40) UNIQUE NOT NULL,
	DATA DATETIME DEFAULT GETDATE() NOT NULL,
	STATUS VARCHAR(7) DEFAULT ('Aberta') NOT NULL,
	PLANO_DE_ENSINO VARCHAR (1000) NOT NULL,
	CARGA_HORARIA TINYINT NOT NULL,
	COMPETENCIAS VARCHAR (100) NOT NULL,
	HABILIDADES VARCHAR (100) NOT NULL,
	EMENDA VARCHAR (500) NOT NULL,
	CONTEUDO_PROGRAMATICO VARCHAR (1000) NOT NULL,
	BIBLIOGRAFIA_BASICA VARCHAR (200) NOT NULL,
	BIBLIOGRAFIA_COMPLEMENTAR VARCHAR (200) NOT NULL,
	PERCENTUAL_PRATICO TINYINT NOT NULL,
	PERCENTUAL_TEORICO TINYINT NOT NULL,
	ID_COORDENADOR INT,
	CONSTRAINT CHK_CARGA_HORARIA CHECK (CARGA_HORARIA= 'Aberta' or CARGA_HORARIA='Fechada'),
	CONSTRAINT CHK_PERCENTUAL_PRATICO CHECK (0<=PERCENTUAL_PRATICO AND PERCENTUAL_PRATICO>=100),
	CONSTRAINT CHK_PERCENTUAL_TEORICO CHECK (0<=PERCENTUAL_TEORICO AND PERCENTUAL_TEORICO>=100),
	CONSTRAINT FK_ID_COORDENADOR FOREIGN KEY (ID_COORDENADOR) REFERENCES Coordenador(ID)
	);

	CREATE TABLE CURSO 
	(
	ID INT PRIMARY KEY IDENTITY,
	NOME VARCHAR (30) UNIQUE NOT NULL
	);

CREATE TABLE DISCIPLINA_OFERTADA
	(
	ID SMALLINT PRIMARY KEY IDENTITY,
	ID_COORDENADOR INT,
	DtINICIO_MATRICULA DATE,
	DtFIM_DA_MATRICULA DATE,
	ID_DISCIPLINA SMALLINT NOT NULL,
	ID_CURSO INT NOT NULL,
	SEMESTRE TINYINT CHECK (SEMESTRE=1 OR SEMESTRE=2) NOT NULL,
	TURMA CHAR(1) CHECK (TURMA>='A' AND TURMA<='Z') NOT NULL,
	ID_PROFESSOR INT,
	ANO INT CHECK (ANO>=1900 AND ANO<=2100) NOT NULL,
	METODOLOGIA VARCHAR(1000),
	RECURSOS VARCHAR (1000),
	CRITERIO_AVALIACAO VARCHAR (1000),
	PLANO_DE_AULA VARCHAR (1000),
	CONSTRAINT FK_ID_COORDENADORDISCIPLINA FOREIGN KEY (ID_COORDENADOR) REFERENCES Coordenador(ID),
	CONSTRAINT FK_ID_DISCIPLINA FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA(ID),
	CONSTRAINT FK_ID_CURSO FOREIGN KEY (ID_CURSO) REFERENCES Curso(ID),
	CONSTRAINT FK_ID_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES Professor(ID)
	);

CREATE TABLE SOLICITACAO_MATRICULA
	(
	ID INT PRIMARY KEY IDENTITY ,
	IdAluno INT NOT NULL,
	IdDisciplinaOfertada SMALLINT NOT NULL,
	DtSolicitação DATE DEFAULT GETDATE() NOT NULL ,		
	IdCoordenador INT ,
	STATUS CHAR (12) DEFAULT ('Solicitada'),
	CONSTRAINT CHK_STATUS CHECK (STATUS='Solicitada' or STATUS= 'Aprovada' or STATUS= 'Rejeitada' or STATUS= 'Cancelada'),
	--CONSTRAINT DF_STATUS DEFAULT ('Solicitada'),
	CONSTRAINT FK_ID_ALUNO1 FOREIGN KEY (IdAluno) REFERENCES Aluno(ID),
	CONSTRAINT FK_ID_DISC_OFERTADA1 FOREIGN KEY (IdDisciplinaOfertada) REFERENCES DISCIPLINA_OFERTADA(ID),
	CONSTRAINT FK_ID_COORDENADOR_MATRICULA FOREIGN KEY (IdCoordenador) REFERENCES Coordenador(ID)
	);

CREATE TABLE ATIVIDADE
(
	ID	INT PRIMARY KEY NOT NULL,
	TITULO VARCHAR (100) UNIQUE NOT NULL,
	DESCRICAO CHAR,
	CONTEUDO VARCHAR (1000) NOT NULL,
	TIPO CHAR (7) NOT NULL,
	EXTRAS VARCHAR (100),
	IDPROFESSOR	INT NOT NULL,
	CONSTRAINT CHK_TIPO CHECK (TIPO = 'RESPOSTA ABERTA' AND TIPO = 'TESTE'),
	CONSTRAINT FK_ID_PROFESSOR_ATVD FOREIGN KEY (IDPROFESSOR) REFERENCES Professor(ID)
	);

	CREATE TABLE ATIVIDADEVINCULADA
(
	ID	INT PRIMARY KEY IDENTITY,
	IDATIVIDADE INT UNIQUE NOT NULL,
	IDPROFESSOR	INT NOT NULL,
	IDDISCIPLINAOFERTADA SMALLINT UNIQUE NOT NULL,
	ROTULO CHAR (50) UNIQUE NOT NULL, 
	STATUS CHAR NOT NULL,
	DTINICIORESPOSTAS DATE NOT NULL,
	DTFIMRESPOSTA DATE NOT NULL,
	CONSTRAINT CHK_STATUS_ATVD CHECK (STATUS = 'DISPONIBILIZADA' OR STATUS = 'ABERTA' OR STATUS = 'FECHADA' OR STATUS = 'ENCERRADA' OR STATUS = 'PRORROGADA'),
	CONSTRAINT FK_ID_ATIVIDADE_VINC FOREIGN KEY (IDATIVIDADE) REFERENCES ATIVIDADE(ID),
	CONSTRAINT FK_ID_PROFESSOR_ATVD_VINC FOREIGN KEY(IDPROFESSOR) REFERENCES Professor(ID),
	CONSTRAINT FK_ID_DISC_OFERTADA_ATVD FOREIGN KEY (IDDISCIPLINAOFERTADA) REFERENCES DISCIPLINA_OFERTADA(ID)

	);

CREATE TABLE Entrega
(
ID INT PRIMARY KEY IDENTITY,
IdAluno1 INT NOT NULL,
IdAtividadeVinculada1 INT NOT NULL,
Titulo VARCHAR(20) NOT NULL,
Resposta VARCHAR(50)NOT NULL,
DtEntrega DATETIME DEFAULT GETDATE(),
Status VARCHAR(9) DEFAULT('ENTREGUE') CHECK(Status='Entregue' or Status='Corrigido'),
IdProfessor INT,
Nota DECIMAL(4,2) CHECK(NOTA>=0.00 or NOTA<=10.00),
DtAvaliacao DATE,
OBS VARCHAR(200),
CONSTRAINT FK_ID_ALUNO_1 FOREIGN KEY (IdAluno1) REFERENCES Aluno(ID),
CONSTRAINT FK_ID_ATVD_VINC1 FOREIGN KEY (IdAtividadeVinculada1) REFERENCES ATIVIDADEVINCULADA(ID),
CONSTRAINT FK_ID_PROF FOREIGN KEY (IdProfessor) REFERENCES Professor(ID)
);
	
CREATE TABLE MENSAGEM
  (
  ID INT PRIMARY KEY NOT NULL,
  IdAluno INT NOT NULL,
  IdProfessor INT NOT NULL,
  Assunto VARCHAR (500) NOT NULL,
  Referência VARCHAR (200) NOT NULL,
  Conteúdo VARCHAR (1000) NOT NULL,
  STATUS CHAR (10) NOT NULL,
  DtEnvio DATE DEFAULT GETDATE() NOT NULL,
  DtResposta DATE,
  Resposta CHAR (30),
  CONSTRAINT CHK_STATUS_MSG CHECK(STATUS=' Enviado' or STATUS= 'Lido' or STATUS= 'Respondido'),
  CONSTRAINT FK_ID_ALUNO_2 FOREIGN KEY (IdAluno) REFERENCES Aluno(ID),
  CONSTRAINT FK_ID_PROF_1 FOREIGN KEY (IdProfessor) REFERENCES Professor(ID),
  );


