--CRIA TABELA UNIDADES
create table UNIDADES(
COD_UNIT INT IDENTITY, 
NOME VARCHAR(35),
CONSTRAINT PK_UNIDADE PRIMARY KEY(COD_UNIT)
);
--INSERE DADOS NA TABELA UNIDADES
INSERT INTO UNIDADES VALUES ('PEÇAS'),('METROS'),('QUILOGRAMAS'),('DÚZIAS'),('PACOTE'),('CAIXA');
--CRIA A TABELA CATEGORIA
CREATE TABLE CATEGORIAS(
COD_CAT INT IDENTITY,
NOME VARCHAR(35),
CONSTRAINT PK_CATEGORIAS PRIMARY KEY(COD_CAT) 
);
--INSERE DADOS NA TABELA CATEGORIA
INSERT INTO CATEGORIAS VALUES('MOUSE'),('PEN-DRIVE'),('MONITOR DE VIDEO'),('TECLADO'),('CPU'),('CABO DE REDE');
--CRIA TABELA PRODUTOS
CREATE TABLE PRODUTOS(
COD_PROD INT IDENTITY,
NOME_PRODUTO VARCHAR(36) NOT NULL,
COD_UNIT INT,
USE EXEMPLO;

COD_CAT INT,
QTD_ESTOQUE SMALLINT,
QTD_MIN SMALLINT,
PC_CUSTO NUMERIC(5,2),
PC_VENDA NUMERIC(5,2),
DESCR      TEXT,
CONSTRAINT PK_PRODUTO PRIMARY KEY(COD_PROD),
CONSTRAINT FK_UNIDADE FOREIGN KEY(COD_UNIT) REFERENCES UNIDADES(COD_UNIT),
CONSTRAINT FK_CATEGORIA FOREIGN KEY(COD_CAT) REFERENCES CATEGORIAS(COD_CAT)
);
--INSERE DADOS NA TABELA PRODUTOS
INSERT INTO PRODUTOS(NOME_PRODUTO,COD_UNIT,COD_CAT,QTD_ESTOQUE,QTD_MIN,PC_CUSTO,PC_VENDA) VALUES
('CANETA AZUL',1,1,150,40,0.5,0.75),('CANETA VERDE',1,1,50,40,0.5,0.75),
('CANETA VERMELHA',1,1,80,35,0.5,0.75),('LAPIS',1,1,400,80,0.5,0.8),('RÉGUA',1,1,40,10,1,1.5);
SELECT * FROM PRODUTOS;
-- EXERCICIOS DE ALTERAR DADOS DA TABELA
UPDATE TB_PRODUTO SET PRECO_CUSTO*=1.15 WHERE COD_TIPO=2; 
UPDATE TB_PRODUTO SET PRECO_VENDA = PRECO_CUSTO*1.3 WHERE COD_TIPO=2;
UPDATE TB_PRODUTO SET IPI=5 WHERE COD_TIPO=3;
UPDATE TB_PRODUTO SET QTD_MINIMA*=0.9;
UPDATE TB_CLIENTE SET ENDERECO='AV. CELSO GARCIA, 1234',BAIRRO='TATUAPE',CIDADE='SAO PAULO',ESTADO='SP',CEP='03407080' WHERE CODCLI=11;
UPDATE TB_CLIENTE SET END_COB=ENDERECO,BAI_COB=BAIRRO,CID_COB=CIDADE,EST_COB=ESTADO,CEP_COB=CEP WHERE CODCLI=13;
UPDATE TB_CLIENTE SET ICMS =12 WHERE ESTADO IN ('RJ', 'RO', 'AC', 'RR', 'MG', 'PR', 'SC', 'RS', 'MS', 'MT');
UPDATE TB_CLIENTE SET ICMS =18 WHERE ESTADO='SP';
UPDATE TB_CLIENTE SET ICMS =7 WHERE ESTADO NOT IN ('RJ', 'RO', 'AC', 'RR', 'MG', 'PR', 'SC', 'RS', 'MS', 'MT','SP');
UPDATE TB_ITENSPEDIDO SET DESCONTO=7 WHERE (ID_PRODUTO=8) AND (DATA_ENTREGA BETWEEN '2007-1-1' AND '2007-1-31') AND QUANTIDADE >1000;
UPDATE TB_ITENSPEDIDO SET DESCONTO = 0 WHERE QUANTIDADE < 1000 AND(DATA_ENTREGA > '2007-6-1') AND DESCONTO >0;
SELECT * INTO VENDEDORES_TMP FROM TB_VENDEDOR;
DELETE VENDEDORES_TMP WHERE CODVEN >5;
SELECT * INTO COPIA_PEDIDOS FROM TB_PEDIDO;
DELETE COPIA_PEDIDOS WHERE CODVEN = 2;
DELETE COPIA_PEDIDOS WHERE (MONTH(DATA_EMISSAO)<='6' AND MONTH(DATA_EMISSAO) >=1) AND YEAR(DATA_EMISSAO)='2007';
TRUNCATE TABLE COPIA_PEDIDOS;
