-- EXCLUINDO TABELAS, CASO EXISTAM
IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'MENSAGEM')
	DROP TABLE MENSAGEM;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ENTREGA')
	DROP TABLE ENTREGA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ATIVIDADEVINCULADA')
	DROP TABLE ATIVIDADEVINCULADA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ATIVIDADE')
	DROP TABLE ATIVIDADE;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'SOLICITACAOMATRICULA')
	DROP TABLE SOLICITACAOMATRICULA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'DISCIPLINAOFERTADA')
	DROP TABLE DISCIPLINAOFERTADA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'DISCIPLINA')
	DROP TABLE DISCIPLINA;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'ALUNO')
	DROP TABLE ALUNO;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'PROFESSOR')
	DROP TABLE PROFESSOR;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'COORDENADOR')
	DROP TABLE COORDENADOR;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'USUARIO')
	DROP TABLE USUARIO;

IF EXISTS (SELECT * FROM SYS.TABLES WHERE NAME = 'CURSO')
	DROP TABLE CURSO;

-- TABELA USUARIO
CREATE TABLE USUARIO
(
	ID				INT			IDENTITY,
	LOGIN			VARCHAR(30) NOT NULL,
	SENHA			CHAR(8)		NOT NULL,
	DTEXPIRACAO		DATE		NOT NULL	CONSTRAINT DF_USU_DTEXP	DEFAULT ('1900/01/01'), 

	CONSTRAINT PK_USU		PRIMARY KEY (ID),
	CONSTRAINT UQ_USU_LOGIN	UNIQUE (LOGIN),
	CONSTRAINT CK_USU_SENHA	CHECK ( LEN(SENHA) = 8) -- EXTRA: SENHA OBRIGATORIAMENTE TERA 8 CARACTERES
);

-- TABELA ALUNO
CREATE TABLE ALUNO
(
	ID			INT				IDENTITY,
	IDUSUARIO	INT				NOT NULL,
	NOME		VARCHAR(50)		NOT NULL,
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL,
	RA			CHAR(7)			NOT NULL, 
	FOTO		VARCHAR(100)	,

	CONSTRAINT PK_ALUNO		PRIMARY KEY (ID),
	CONSTRAINT UQ_ALU_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_ALU_CELUL UNIQUE (CELULAR),
	CONSTRAINT UQ_ALU_RA	UNIQUE (RA) -- EXTRA: RA NÃO PODE DUPLICAR
);

--TABELA COORDENADOR
CREATE TABLE COORDENADOR
(
	ID			SMALLINT				IDENTITY,
	IDUSUARIO	INT				NOT NULL,
	NOME		VARCHAR(50)		NOT NULL,
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL

	CONSTRAINT PK_COORD		PRIMARY KEY (ID),
	CONSTRAINT UQ_COO_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_COO_CELUL UNIQUE (CELULAR)
);

--TABELA PROFESSOR
CREATE TABLE PROFESSOR
(
	ID			SMALLINT		IDENTITY,
	IDUSUARIO	INT,
	NOME		VARCHAR(50)		NOT NULL,  -- EXTRA: AJUSTE DO MODELO, FALTAVA O NOME DO PROF
	EMAIL		VARCHAR(50)		NOT NULL,
	CELULAR		CHAR(11)		NOT NULL,
	APELIDO		VARCHAR(50)		NOT NULL

	CONSTRAINT PK_PROFE		PRIMARY KEY (ID),
	CONSTRAINT UQ_PRO_EMAIL UNIQUE (EMAIL),
	CONSTRAINT UQ_PRO_CELUL UNIQUE (CELULAR)
);

-- TABELA DISCIPLINA
CREATE TABLE DISCIPLINA
(
	ID					     SMALLINT		IDENTITY,
	NOME					 VARCHAR(100)	NOT NULL,
	DATA					 DATE			NOT NULL CONSTRAINT DF_DIS_DATA	DEFAULT (GETDATE()),
	STATUS					 VARCHAR(10)	NOT NULL CONSTRAINT DF_DIS_STAT	DEFAULT ('ABERTA'),
	PLANODEENSINO			 VARCHAR(1000)	NOT NULL,
	CARGAHORARIA			 TINYINT		NOT NULL,
	COMPETENCIAS			 VARCHAR(1000)	NOT NULL,
	HABILIDADES				 VARCHAR(1000)	NOT NULL,
	EMENTA					 VARCHAR(1000)	NOT NULL,
	CONTEUDOPROGRAMATICO	 VARCHAR(1000)	NOT NULL,
	BIBLIOGRAFIABASICA		 VARCHAR(1000)	NOT NULL,
	BIBLIOGRAFIACOMPLEMENTAR VARCHAR(1000)	NOT NULL,
	PERCENTUALPRATICO		 TINYINT		NOT NULL,
	PERCENTUALTEORICO		 TINYINT		NOT NULL,
	IDCOORDENADOR			 SMALLINT		NOT NULL,
	
	CONSTRAINT PK_DISCI		PRIMARY KEY (ID),
	CONSTRAINT UQ_DIS_NOME	UNIQUE (NOME),
	CONSTRAINT CK_DIS_STAT	CHECK ( STATUS IN ('ABERTA', 'FECHADA' )),
	CONSTRAINT CK_DIS_CARG	CHECK ( CARGAHORARIA IN (40,80)),
	CONSTRAINT CK_DIS_PERP	CHECK ( PERCENTUALPRATICO BETWEEN 0 and 100),
	CONSTRAINT CK_DIS_PERT	CHECK ( PERCENTUALTEORICO BETWEEN 0 AND 100),
	CONSTRAINT CK_DIS_PERC	CHECK ( PERCENTUALTEORICO + PERCENTUALPRATICO = 100 )  -- EXTRA: PERC PRATICO + TEORICO = 100%
);

-- TABELA DISCIPLINA OFERTADA
CREATE TABLE DISCIPLINAOFERTADA
(
	ID					    INT			IDENTITY,
	IDCOORDENADOR			SMALLINT	NOT NULL,
	DTINICIOMATRICULA		DATE,
	DTFIMMATRICULA			DATE,
	IDDISCIPLINA			SMALLINT	NOT NULL,
	IDCURSO					TINYINT		NOT NULL,
	ANO						SMALLINT	NOT NULL,
	SEMESTRE				TINYINT		NOT NULL,
	TURMA					CHAR(1)		NOT NULL,
	IDPROFESSOR				SMALLINT,
	METODOLOGIA				VARCHAR(1000),
	RECURSOS				VARCHAR(1000),
	CRITERIOAVALIACAO		VARCHAR(1000),
	PLANODEAULAS			VARCHAR(1000),

	CONSTRAINT PK_DOFER		PRIMARY KEY (ID),
	CONSTRAINT CK_DOFER_ANO CHECK(ANO BETWEEN 1900 AND 2100),
	CONSTRAINT CK_DOFER_SEM CHECK(SEMESTRE IN (1,2)),
	CONSTRAINT CK_DOFER_TUR CHECK(TURMA BETWEEN 'A' AND 'Z'),
	CONSTRAINT CK_DOFER_PRO CHECK 
		(CASE 
			WHEN IDPROFESSOR  IS NULL 
			THEN 1
			WHEN IDPROFESSOR  IS NOT NULL AND METODOLOGIA IS NOT NULL AND
				 RECURSOS	  IS NOT NULL AND CRITERIOAVALIACAO IS NOT NULL AND
				 PLANODEAULAS IS NOT NULL 
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM PROF OK. CASO PROF TEM QUE TER METODOLOGIA, RECURSO, CRITERIO E PLANO.
	CONSTRAINT UQ_DOFER_COM	UNIQUE (IDDISCIPLINA, IDCURSO, ANO, SEMESTRE, TURMA)
);				 

--TABELA CURSO
CREATE TABLE CURSO
(
	ID		TINYINT		IDENTITY,
	NOME	VARCHAR(50)	NOT NULL,

	CONSTRAINT PK_CURSO			PRIMARY KEY (ID),
	CONSTRAINT UQ_CURSO_NOME	UNIQUE (NOME)
);


-- TABELA SOLICITACAO MATRICULA
CREATE TABLE SOLICITACAOMATRICULA
(
	ID				INT			IDENTITY,
	IDALUNO			INT			NOT NULL,
	IDDOFERTADA		INT			NOT NULL,
	DTSOLICITACAO	DATETIME	NOT NULL CONSTRAINT DF_SMATRI_DT DEFAULT (GETDATE()),
	IDCOORDENADOR	SMALLINT, 
	STATUS			VARCHAR(15)	NOT NULL CONSTRAINT DF_SMATRI_ST DEFAULT ('SOLICITADA'),

	CONSTRAINT	PK_SMATRI	 PRIMARY KEY (ID),
	CONSTRAINT	CK_SMATRI_ST CHECK (STATUS IN ('SOLICITADA', 'APROVADA','REJEITADA', 'CANCELADA' ))
);

-- TABELA ATIVIDADE
CREATE TABLE ATIVIDADE
(
	ID				INT				IDENTITY,
	TITULO			VARCHAR(30)		NOT NULL,
	DESCRICAO		VARCHAR(100),
	CONTEUDO		VARCHAR(8000)	NOT NULL,
	TIPO 			VARCHAR(15)		NOT NULL, 
	EXTRAS			VARCHAR(100),
	IDPROFESSOR		SMALLINT,

	CONSTRAINT	PK_ATIVIDADE	PRIMARY KEY (ID),
	CONSTRAINT	UQ_ATIVI_TITU	UNIQUE (TITULO),	 
	CONSTRAINT	CK_ATIVI_TIPO	CHECK (TIPO IN ('RESPOSTA ABERTA', 'TESTE')),
);

-- TABELA ATIVIDADE VINCULADA
CREATE TABLE ATIVIDADEVINCULADA
(
	ID				INT			 IDENTITY,
	IDATIVIDADE		INT			 NOT NULL,
	IDPROFESSOR		SMALLINT	 NOT NULL,
	IDDOFERTADA		INT			 NOT NULL,
	ROTULO			VARCHAR(100) NOT NULL,
	STATUS			VARCHAR(15)	 NOT NULL,
	DTINIRESPOSTA	DATETIME	 NOT NULL,
	DTFIMRESPOSTA	DATETIME	 NOT NULL,

	CONSTRAINT	PK_AVINCULADA	PRIMARY KEY (ID),
	CONSTRAINT	UQ_AVINC		UNIQUE (ROTULO, IDATIVIDADE, IDDOFERTADA),
	CONSTRAINT  CK_AVINC_STAT	CHECK (STATUS IN ('DISPONIBILIZADA','ABERTA', 'FECHADA','ENCERRADA','PRORROGADA'))
);

-- TABELA ENTREGA
CREATE TABLE ENTREGA
(
	ID				INT				IDENTITY,
	IDALUNO			INT				NOT NULL,
	IDAVINCULADA	INT				NOT NULL,
	TITULO			VARCHAR(100)	NOT NULL,
	RESPOSTA		VARCHAR(8000)	NOT NULL,
	DTENTREGA		DATETIME		NOT NULL CONSTRAINT DF_ENTRE_DTEN DEFAULT (GETDATE()),
	STATUS			VARCHAR(10)		NOT NULL CONSTRAINT DF_ENTRE_STAT	DEFAULT	('ENTREGUE'),
	IDPROFESSOR		SMALLINT,
	NOTA			DECIMAL(4,2),
	DTAVALIACAO		DATETIME,
	OBS				VARCHAR(500),

	CONSTRAINT	PK_ENTREGA		PRIMARY KEY (ID),
	CONSTRAINT  UQ_ENTRE		UNIQUE (IDALUNO, IDAVINCULADA),
	CONSTRAINT  CK_ENTRE_STAT	CHECK (STATUS IN ('ENTREGUE','CORRIGIDO')),
	CONSTRAINT  CK_ENTRE_NOTA	CHECK (NOTA BETWEEN 0 AND 10),
	CONSTRAINT	CK_ENTRE_CORR	CHECK
		(CASE 
			WHEN IDPROFESSOR  IS NULL 
			THEN 1
			WHEN IDPROFESSOR  IS NOT NULL AND 
				 NOTA IS NOT NULL AND
				 DTAVALIACAO = GETDATE() AND 
				 STATUS = 'CORRIGIDO'
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM PROF OK. CASO PROF CORRIGIR, TEM QUE TER NOTA E DATA TEM QUE SER DATA/HORA ATUAL.
)

-- TABELA MENSAGEM
CREATE TABLE MENSAGEM
(
		ID				INT				IDENTITY,
		IDALUNO			INT				NOT NULL,
		IDPROFESSOR		SMALLINT		NOT NULL,
		ASSUNTO			VARCHAR(100)	NOT NULL,
		REFERENCIA		VARCHAR(100)	NOT NULL,
		CONTEUDO		VARCHAR(500)	NOT NULL,
		STATUS			VARCHAR(10)		NOT NULL CONSTRAINT DF_MENSA_STAT DEFAULT 'ENVIADO',
		DTENVIO			DATETIME		NOT NULL CONSTRAINT DF_MENSA_DTEN DEFAULT GETDATE(),
		DTRESPOSTA		DATETIME,
		RESPOSTA		VARCHAR(500),
		
		CONSTRAINT	PK_MENSAGEM		PRIMARY KEY (ID),
		CONSTRAINT	CK_MENSA_STAT	CHECK (STATUS IN ( 'ENVIADO', 'LIDO', 'RESPONDIDO' )),
		CONSTRAINT	CK_MENSA_RESP	CHECK
		(CASE 
			WHEN DTRESPOSTA  IS NULL 
			THEN 1
			WHEN DTRESPOSTA  IS NOT NULL AND 
				 RESPOSTA IS NOT NULL AND
				 STATUS = 'RESPONDIDO'
			THEN 1
			ELSE 0
		END = 1), -- EXTRA VALIDAÇÃO SE ESTIVER SEM DTRESPOSTA OK. CASO MENSAGEM RESPONDIDA, TEM QUE TER DTRESPOSTA, RESPOSTA E STATUS TEM QUE SER RESPONDIDO.
)

-- INCLUINDO AS FKs

ALTER TABLE COORDENADOR ADD
	CONSTRAINT FK_COORD_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE PROFESSOR ADD
	CONSTRAINT FK_PROFE_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE ALUNO ADD
	CONSTRAINT FK_ALUNO_USU	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (ID);

ALTER TABLE DISCIPLINA ADD
	CONSTRAINT FK_DISCI_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID);

ALTER TABLE DISCIPLINAOFERTADA ADD
	CONSTRAINT FK_DOFER_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID),
	CONSTRAINT FK_DOFER_DISCI FOREIGN KEY (IDDISCIPLINA)  REFERENCES DISCIPLINA (ID),
	CONSTRAINT FK_DOFER_CURSO FOREIGN KEY (IDCURSO)		  REFERENCES CURSO (ID),
	CONSTRAINT FK_DOFER_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE SOLICITACAOMATRICULA ADD
	CONSTRAINT FK_SMATR_COORD FOREIGN KEY (IDCOORDENADOR) REFERENCES COORDENADOR (ID),
	CONSTRAINT FK_SMATR_DISCI FOREIGN KEY (IDDOFERTADA)   REFERENCES DISCIPLINAOFERTADA (ID),
	CONSTRAINT FK_SMATR_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);

ALTER TABLE ATIVIDADE ADD
	CONSTRAINT FK_ATIV_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE ATIVIDADEVINCULADA ADD
	CONSTRAINT FK_AVINC_ATIVI FOREIGN KEY (IDATIVIDADE)	  REFERENCES ATIVIDADE (ID),
	CONSTRAINT FK_AVINC_DISCI FOREIGN KEY (IDDOFERTADA)   REFERENCES DISCIPLINAOFERTADA (ID),
	CONSTRAINT FK_AVINC_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID);

ALTER TABLE ENTREGA ADD
	CONSTRAINT FK_ENTRE_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID),
	CONSTRAINT FK_ENTRE_AVINC FOREIGN KEY (IDAVINCULADA)  REFERENCES ATIVIDADEVINCULADA (ID),
	CONSTRAINT FK_ENTRE_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);

ALTER TABLE MENSAGEM ADD
	CONSTRAINT FK_MENSA_PROFE FOREIGN KEY (IDPROFESSOR)   REFERENCES PROFESSOR (ID),
	CONSTRAINT FK_MENSA_ALUNO FOREIGN KEY (IDALUNO)		  REFERENCES ALUNO (ID);

------------------------------------------------------------------------------------------------------------


-- INICIO DOS EXERCÍCIOS
-- INSERIR DADOS DE USUÁRIOS(NOME, LOGINS E SENHAS)

INSERT INTO USUARIO(LOGIN, SENHA) VALUES
('GILSON.ALMEIDA', 'G1501375'),
('SEBASTIAO.RODRIGUES', 'S1602440'),
('VALDIR.CASTRO', 'V1602396'),
('LUIZ.MELO', 'L1701777'),
('FRANCISCO.JESUS', 'F1602405'),
('NELSON.MOREIRA', 'N1602128'),
('RAIMUNDO.MORAES', 'R1602230'),
('FABIO.MOURA', 'F1601249'),
('ANDRE.COSTA', 'A1701595'),
('MARCIO.BATISTA', 'M1601576'),
('VINICIUS.CONCEICAO', 'V1501650'),
('JOAO.SOUSA', 'J1702249'),
('ANTONIO.MAGALHAES', 'A1702525'),
('JOSE.MORAIS', 'J1501148'),
('JONATHAN.FILHO', 'J1502810'),
('PAULO.MELO', 'P1602770'),
('ALESSANDRO.DIAS', 'A1602697'),
('EVERTON.MARTINS', 'E1602173'),
('EDSON.FERNANDES', 'E1601713'),
('EMERSON.MENEZES', 'E1602326'),
('CICERO.SANTANA', 'C1501257'),
('MICHELE.GARCIA', 'M1501464'),
('DOUGLAS.XAVIER', 'D1502465'),
('RODRIGO.GOMES', 'R1502808'),
('ALEXANDRE.DIAS', 'A1601975'),
('MAURO.CARVALHO', 'M1702530'),
('EDUARDO.VIEIRA', 'E1602305'),
('FABRICIO.MACHADO', 'F1701582'),
('DANIEL.ROCHA', 'D1501352'),
('JEAN.NEVES', 'J1701910'),
('TAMIRES.CAVALCANTE', 'T1701166'),
('DIEGO.NETO', 'D1502850'),
('MARCELO.SANTOS', 'M1602346'),
('LEONARDO.CUNHA', 'L1601418'),
('ALAN.AGUIAR', 'A1702476'),
('ADRIANA.MACHADO', 'A1702619'),
('MARIA.NASCIMENTO', 'M1502116'),
('ANA.FARIAS', 'A1702648'),
('RENATA.COSTA', 'R1702436'),
('VERA.CARDOSO', 'V1602388'),
('ELIANE.MENDES', 'E1701548'),
('JESSICA.PEREIRA', 'J1502514'),
('PRISCILA.FARIAS', 'P1601584'),
('ROSANGELA.RIBEIRO', 'R1502845'),
('LUCIANA.FERREIRA', 'L1601609'),
('ELAINE.BRAGA', 'E1702717'),
('ANTONIA.FILHO', 'A1602719'),
('PATRICIA.MORAIS', 'P1601963'),
('MARIA.MORAES', 'M1602611'),
('CLAUDIA.MOURA', 'C1601449'),
('ALAN.OLIVEIRA', 'AO123456'),
('ALBERTO.JUNIOR', 'AJ123456'),
('ALEXANDRE.RANGEL', 'AR123456'),
('ALEXANDRE.MARTINS', 'AM123456'),
('ALVARO.TAKEI', 'AT123456'),
('ANA.SANTOS', 'AS123456'),
('BRUNO.KALKEVICIUS', 'BK123456'),
('CEZAR.BELLINI', 'CB123456'),
('EDSON.SILVA', 'ES123456'),
('EDSON.TSUKIMOTO', 'ET123456'),
('EDUARDO.QUEIROZ', 'EQ123456'),
('EMILIO.RESENDE', 'ER123456'),
('FELIPE.DIAS', 'FD123456'),
('FERNANDO.ZUHER', 'FZ123456'),
('FRANCESCA.ROMANELLI', 'FR123456'),
('GISELDA.PEREIRA', 'GP123456'),
('GUILHERME.LOHMANN', 'GL123456'),
('GUSTAVO.FERREIRA', 'GF123456'),
('ILANA.CONCILIO', 'IC123456'),
('IZA.MELÃO', 'IM123456'),
('JOÃO.COUTINHO', 'JC123456'),
('JOSÉ.PRADO', 'JP123456'),
('LEONARDO.TAKUNO', 'LT123456'),
('LUCAS.GONÇALVES', 'LG123456'),
('LUCIANO.CROCCO', 'LC123456'),
('MARCEL.PIRES', 'MP123456'),
('MARCELO.SILVA', 'MS123456'),
('MARCELO.TERRA', 'MT123456'),
('MARCO.JEUNON', 'MJ123456'),
('OSVALDO.TAKAI', 'OT123456'),
('PEDRO.PRADO', 'PP123456'),
('PLÍNIO.FILHO', 'PF123456'),
('RENATO.SANTOS', 'RS123456'),
('RODRIGO.PIASSI', 'RP123456'),
('SÉRGIO.BRUZETTI', 'SB123456'),
('VANDERSON.BOSSI', 'VB123456'),
('VICTOR.OLIVEIRA', 'VO123456'),
('VLADIMIR.CHAGAS', 'VC123456'),
('ALAN.CARVALHO', 'AC123456'),
('BRUNO.LIMA', 'BU123456'),
('AYAO.OKAMOTO', 'AO123456'),
('LUIZ.LIMA', 'LL123456'),
('ANDREA.COSTA', 'AC123456'),
('MICHELLE.MESTRE', 'MM123456');

-- CONSULTAR TABELA USUÁRIO
SELECT * FROM USUARIO


-- INSERINDO DADOS DE ALUNOS(NOME, E-MAIL, TELEFONE, RA)
INSERT INTO ALUNO (IDUSUARIO, NOME, EMAIL, CELULAR,RA) VALUES
(1,'GILSON FERNANDES ALMEIDA','gf_almeida@impacta.com.br','991501375','1501375'),
(2,'SEBASTIAO DE OLIVEIRA RODRIGUES', 'sd_rodrigues@impacta.com.br','991602440', '1602440'),
(3,'VALDIR GOMES DE CASTRO','vg_castro@impacta.com.br','991602396', '1602396'),
(4, 'LUIZ CARLOS DE JESUS MELO', 'ld_melo@impacta.com.br', '991701777', '1701777'),
(5, 'FRANCISCO DE SOUZA JESUS', 'fd_jesus@impacta.com.br', '991602405', '1602405'),
(6, 'NELSON FERREIRA DE MOREIRA', 'nf_moreira@impacta.com.br', '991602128', '1602128'),
(7, 'RAIMUNDO VIEIRA MORAES', 'rv_moraes@impacta.com.br', '991602230', '1602230'),
(8,'FABIO FERNANDES MOURA', 'ff_moura@impacta.com.br', '991601249', '1601249'),
(9, 'ANDRE SANTOS DE COSTA', 'as_costa@impacta.com.br', '991701595', '1701595'),
(10, 'MARCIO DA COSTA BATISTA', 'md_batista@impacta.com.br', '991601576', '1601576'),
(11, 'VINICIUS SOUZA CONCEICAO', 'vs_conceicao@impacta.com.br', '991501650', '1501650'),
(12, 'JOAO BATISTA ALVES DA SOUSA','ja_sousa@impacta.com.br', '991702249', '1702249'),
(13,'ANTONIO CARLOS FERREIRA DE MAGALHAES', 'af_magalhaes@impacta.com.br', '991702525', '1702525'),
(14, 'JOSE CARLOS LIMA MORAIS', 'jl_morais@impacta.com.br', '991501148','1501148'),
(15, 'JONATHAN SANTOS DE FILHO', 'js_filho@impacta.com.br', '991502810','1502810'),
(16,'PAULO RODRIGUES DA MELO', 'pr_melo@impacta.com.br', '991602770', '1602770'),
(17, 'ALESSANDRO  DIAS', 'a_dias@impacta.com.br', '991602697', '1602697'),
(18, 'EVERTON DE OLIVEIRA MARTINS', 'ed_martins@impacta.com.br', '991602173', '1602173'),
(19, 'EDSON APARECIDA DE FERNANDES', 'ea_fernandes@impacta.com.br', '991601713', '1601713'),
(20, 'EMERSON GOMES MENEZES', 'eg_menezes@impacta.com.br', '991602326', '1602326'),
(21,'CICERO PEREIRA DE SANTANA', 'cp_santana@impacta.com.br', '991501257', '1501257'),
(22, 'MICHELE SOUZA GARCIA', 'ms_garcia@impacta.com.br', '991501464', '1501464'),
(23, 'DOUGLAS GONCALVES XAVIER', 'dg_xavier@impacta.com.br', '991502465', '1502465'),
(24, 'RODRIGO REGINA GOMES', 'rr_gomes@impacta.com.br', '991502808', '1502808'),
(25, 'ALEXANDRE DE JESUS DIAS', 'ad_dias@impacta.com.br', '991601975', '1601975'),
(26, 'MAURO DE JESUS CARVALHO', 'md_carvalho@impacta.com.br', '991702530', '1702530'),
(27, 'EDUARDO  VIEIRA', 'e_vieira@impacta.com.br', '991602305', '1602305'),
(28, 'FABRICIO REGINA MACHADO', 'fr_machado@impacta.com.br', '991701582', '1701582'),
(29, 'DANIEL FERREIRA DE ROCHA', 'df_rocha@impacta.com.br', '991501352', '1501352'),
(30, 'JEAN DA COSTA NEVES', 'jd_neves@impacta.com.br', '991701910', '1701910'),
(31, 'TAMIRES PEREIRA DE CAVALCANTE', 'tp_cavalcante@impacta.com.br', '991701166', '1701166'),
(32, 'DIEGO REGINA NETO', 'dr_neto@impacta.com.br', '991502850', '1502850'),
(33, 'MARCELO DOS SANTOS', 'md_santos@impacta.com.br', '991602346', '1602346'),
(34, 'LEONARDO RODRIGUES DE CUNHA', 'lr_cunha@impacta.com.br', '991601418', '1601418'),
(35,'ALAN ALVES AGUIAR', 'aa_aguiar@impacta.com.br', '991702476', '1702476'),
(36, 'ADRIANA FERNANDES MACHADO', 'af_machado@impacta.com.br', '991702619', '1702619'),
(37,'MARIA BARBOSA NASCIMENTO', 'mb_nascimento@impacta.com.br', '991502116', '1502116'),
(38,'ANA PAULA FERREIRA DE FARIAS', 'af_farias@impacta.com.br', '991702648','1702648'),
(39, 'RENATA VIEIRA COSTA', 'rv_costa@impacta.com.br', '991702436', '1702436'),
(40,'VERA  CARDOSO', 'v_cardoso@impacta.com.br', '991602388', '1602388'),
(41, 'ELIANE BARBOSA MENDES', 'eb_mendes@impacta.com.br', '991701548', '1701548'),
(42, 'JESSICA DE OLIVEIRA PEREIRA', 'jd_pereira@impacta.com.br', '991502514', '1502514'),
(43, 'PRISCILA MARIA DE FARIAS', 'pm_farias@impacta.com.br', '991601584', '1601584'),
(44, 'ROSANGELA PEREIRA DE RIBEIRO', 'rp_ribeiro@impacta.com.br', '991502845', '1502845'),
(45, 'LUCIANA MARIA FERREIRA', 'lm_ferreira@impacta.com.br', '991601609','1601609'),
(46, 'ELAINE SOARES BRAGA', 'es_braga@impacta.com.br', '991702717', '1702717'),
(47, 'ANTONIA FERREIRA FILHO', 'af_filho@impacta.com.br', '991602719', '1602719'),
(48, 'PATRICIA DE SOUZA MORAIS', 'pd_morais@impacta.com.br', '991601963', '1601963'),
(49, 'MARIA JOSE APARECIDA MORAES', 'ma_moraes@impacta.com.br', '991602611', '1602611'),
(50, 'CLAUDIA DE LIMA MOURA', 'cd_moura@impacta.com.br', '991601449', '1601449');


-- CONSULTA TABELA ALUNO
SELECT * FROM ALUNO 

-- INSERINDO DADOS COORDENADORES(IDUSUARIO, NOME, EMAIL, CELULAR)
INSERT INTO COORDENADOR (IDUSUARIO, NOME, EMAIL, CELULAR) VALUES
(56, 'ANA CRISTINA DOS SANTOS', 'ana.santos@impacta.edu.br', '11987654321'),
(65, 'FRANCESCA ROMANELLI', 'f.romanelli@impacta.edu.br', '11999654323'),
(80, 'OSVALDO KOTARO TAKAI', 'osvaldo.takai@impacta.edu.br', '11987655513'),
(90, 'BRUNO LUIS SOARES DE LIMA', 'blima@impacta.edu.br', '11977654321'),
(89, 'ALAN HENRIQUE PARDO DE CARVALHO', 'alan.carvalho@impacta.edu.br', '11966655511'),
(91, 'AYAO OKAMOTO', 'Ayao.Okamoto@impacta.edu.br', '11963654610'),
(92, 'LUIS SOARES DE LIMA', 'luis.lima@impacta.edu.br', '11945654008');

-- CONSULTA TABELA COORDENADOR
SELECT * FROM COORDENADOR

-- INSERINDO DADOS DOS PROFESSORES (IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO)
INSERT INTO PROFESSOR ( IDUSUARIO, NOME, EMAIL, CELULAR, APELIDO) VALUES 
(51, 'ALAN ALVES DE OLIVEIRA', 'aa_oliveira@impacta.com.br', '11999123456','ALAN'),
(52, 'ALBERTO DE MEDEIROS JUNIOR', 'am_junior@impacta.com.br', '11999815321', 'ALBERTO'),
(53, 'ALEXANDRE LEITE RANGEL', 'al_rangel@impacta.com.br', '11999815123', 'RANGEL'),
(54, 'ALEXANDRE LOCCI MARTINS', 'al_martins@impacta.com.br', '11999816842', 'MARTINS'),
(55, 'ALVARO TOSHIO TAKEI', 'at_takei@impacta.com.br', '11999815632', 'ALVARO'),
(56, 'ANA CRISTINA DOS SANTOS', 'ana.santos@impacta.edu.br', '11987654321', 'ANA'),
(57, 'BRUNO ROBERTO KALKEVICIUS', 'br_kalkevicius@impacta.com.br', '11999847155','BRUNO'),
(58, 'CEZAR BELLINI', 'c_bellini@impacta.com.br', '11999842513', 'CEZAR'),
(59, 'EDSON BENITES SILVA', 'eb_silva@impacta.com.br', '11998541239', 'EDSON'),
(60 , 'EDSON TIHARU TSUKIMOTO' , 'et_tsukimoto@impacta.com.br', '11999845123', 'TSUKIMOTO'),
(61, 'EDUARDO LUIS DE QUEIROZ', 'el_queiroz@impacta.com.br', '11998154268', 'EDU'),
(62, 'EMILIO MURTA RESENDE', 'em_resende@impacta.com.br', '11998542132', 'EMILIO'),
(63, 'FELIPE AUGUSTO ROCHA DIAS', 'fa_dias@impacta.com.br', '11998781235', 'FELIPE'),
(64, 'FERNANDO ZUHER', 'f_zuher@impacta.com.br', '11997881235', 'FERNANDO'),
(65, 'FRANCESCA ROMANELLI', 'f.romanelli@impacta.edu.br', '11999654323', 'FRANCESCA'),
(66, 'GISELDA FERNANDA PEREIRA', 'gf_pereira@impacta.com.br', '11998781234', 'GISELDA'),
(67, 'GUILHERME GARCEZ LOHMANN', 'gg_lohmann@impacta.com.br',  '11998783214', 'GUILHERME'),
(68, 'GUSTAVO MENDES FERREIRA', 'gm_ferreira@impacta.com.br', '11998741258', 'FERREIRA'),
(69, 'ILANA DE ALMEIDA SOUZA CONCILIO', 'ia_concilio@impacta.com.br', '11998523218', 'ILANA'),
(70, 'IZA MELÃO', 'i_melão@impacta.com.br', '11995423982', 'IZA'),
(71, 'JOÃO PAULO VENÂNCIO COUTINHO', 'jp_coutinho@impacta.com.br', '11994523218','JP'),
(72, 'JOSÉ PACHECO DE ALMEIDA PRADO', 'jp_prado@impacta.com.br', '11993251474', 'PACHECO'),
(73,  'LEONARDO MASSAYUKI TAKUNO', 'lm_takuno@impacta.com.br', '11993652148', 'TAKUNO'),
(74, 'LUCAS MENDES MARQUES GONÇALVES', 'lm_gonçalves@impacta.com.br', '11998540231', 'LUCAS'),
(75, 'LUCIANO CROCCO', 'l_crocco@impacta.com.br', '11999582312', 'LUCIANO'),
(76,'MARCEL GINOTTI PIRES', 'mg_pires@impacta.com.br', '11999652314', 'MARCEL'),
(77, 'MARCELO CORREIA DA SILVA', 'mc_silva@impacta.com.br', '11999854238', 'MARCELO'),
(78, 'MARCELO SANSINI TERRA', 'ms_terra@impacta.com.br', '11998428611', 'SANSINI'),
(79, 'MARCO TÚLIO JEUNON', 'mt_jeunon@impacta.com.br', '11999854686', 'MARCO'),
(80, 'OSVALDO KOTARO TAKAI', 'osvaldo.takai@impacta.edu.br', '11987655513', 'TAKAI'),
(81, 'PEDRO FELIPE DO PRADO', 'pf_prado@impacta.com.br', '11979861220', 'PEDRO'),
(82, 'PLÍNIO BARBIERI FILHO', 'pb_filho@impacta.com.br', '11958507126', 'PLINIO'),
(83, 'RENATO DE SOUZA SANTOS', 'rs_santos@impacta.com.br', '11972335624','RENATO'),
(84, 'RODRIGO PIASSI', 'r_piassi@impacta.com.br', '11959296521', 'RODRIGO'),
(85, 'SÉRGIO EDUARDO DI SANTORO BRUZETTI', 'se_bruzetti@impacta.com.br', '11951213121', 'SÉRGIO'),
(86, 'VANDERSON GOMES BOSSI', 'vg_bossi@impacta.com.br', '11998718424', 'VANDERSON'),
(87, 'VICTOR INÁCIO DE OLIVEIRA', 'vi_oliveira@impacta.com.br', '11998732487', 'VICTOR'),
(88, 'VLADIMIR CHAGAS', 'v_chagas@impacta.com.br', '11979242830', 'VLADIMIR'),
(83, 'ANDREA VOLANTE COSTA', 'andrea.costa@impacta.edu.br', '11957242810', 'ANDREA'),
(94, 'MICHELLE BRUNA BILECKI MESTRE', 'michelle.mestre@impacta.edu.br', '11999142800', 'MICHELLE');


-- CONSULTANDO TABELA PROFESSOR
SELECT * FROM PROFESSOR

-- INSERINDO DADOS DE CURSOS (NOME)
INSERT INTO CURSO (NOME) VALUES 
('ADMINISTRAÇÃO'), 
('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS'), 
('ANÁLISE E DESENVOLVIMENTO DE SISTEMAS - EAD'), 
('BANCO DE DADOS'),
('ENGENHARIA DA COMPUTAÇÃO'), 
('GESTÃO DA TECNOLOGIA DA INFORMAÇÃO'), 
('JOGOS DIGITAIS'), 
('PROCESSOS GERENCIAIS'),
('PRODUÇÃO MULTIMÍDIA'), 
('REDES DE COMPUTADORES'), 
('SISTEMAS DE INFORMAÇÃO');

-- CONSULTANDO TABELA CURSO
SELECT * FROM CURSO


-- INSERINDO DADOS DA DISCIPLINA
INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
-- ADMINISTRAÇÃO
('Comunicação e Expressão', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Fundamentos da Administração','PLANO DE ENSINO DA DISCIPLINA',80 , 'COMPETENCIAS DA DISCIPLINA', 'HABILIDADES DA DISCIPLINA' , 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA','BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,2),
('MACROECONOMIA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),
('MATEMATICA APLICADA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,2),
('Modelos de Neg e Empreen', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',40,60,2),
('Pensamento Crítico e Ética', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',20,80,2),
('Análise Exploratória de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,2),
('Contabilidade Financeira', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Microeconomia', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Raciocínio Analítico', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Sociologia e Política', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,2),
('Matemática Financeira', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,2),
('Modelagem de Process de Neg', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Administração Financeira', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Estratégia Organizacional', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,2),
('Gestão de Marketing', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Gestão de Operações', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Gestão Estratégica de Pessoas', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),
('Design Thinking', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,2),
('Direito Aplicado à Adm', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Gestão de Qualidade', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',30,70,2),
('Marketing Avançado', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,2),
('Respo Social Corporativo', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Startup e Inovação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,1),
('Fin Corp e Merc de Capi', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',40,60,2),
('Gestão da Cadeia de Supri', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Gestão de Custos', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),
('Gestão de Proj de Inovação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,2),
('Tomada de Decisão e Neg', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',20,80,2),
('Análise de Viab de Proj', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,2),
('Estratégia Comp e Corp', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',30,70,2),
('Jogos de Estratégias', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,2),
('TCC1', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),
('Governança Corporativa', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Negócios Internacionais', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,2),
('TCC2', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),

-- ANALISE E DESENVOLVIMENTO DE SITEMAS
('Fundamentos de Banco de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,1),
('IoT', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Linguagem de Progrm I', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Lógica de Programação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Ling de Program II', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Linguagem SQL', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Engenharia de Software', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Tecnologia Web', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,1),
('Amb de Dev e Ops - DevOps', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Sociedade e Sustent - Opt', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',0,100,1),
('LIBRAS - Optativa', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',0,100,1),
('Desenv de Aplic Distribuídas', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Análise e Model de Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,1),
('Engenharia de Requisitos', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Interface Homem-Computador', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,1),
('Oficina Projeto Empresa 1', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Desenv para Disp Móveis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',30,70,1),
('Arquitetura e Projeto de Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,1),
('Desenv para IoT', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Qualidade de Software', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('OPE2', 'PLANO DE ENSINO DA DISCIPLINA',80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Legislação e Ética', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',0,100,1),

-- BANCO DE DADOS
('Developing Database', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,1),
('Estrutura de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Data Analytics', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,1),
('Adm de Banco de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1),
('Qualde de Governança de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,1),
('Segurança de Banco de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,1),
('Big Data', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,1),
('Desenv de Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,1),

-- ENGENHARIA DA COMPUTAÇÃO
('Circuitos Dig e Eletic', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Matemática para Engenharia', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,4),
('Banco de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,4),
('Conceitos e Aplicações de Cálc', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,4),
('Ciências do Ambiente', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,4),
('Model e Simulação de Sis Físc', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,4),
('Circuitos Elétricos', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,4),
('Eletric e Magnetismo Aplic', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,4),
('Matemática Discreta', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,4),
('Otimização de Sis Line', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Análise Numérica', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',80,20,4),
('Arq de Comp e Sis Opec', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,4),
('Eletrônica Analógica e Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Ling Formais e Autômatos', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',50,50,4),
('Robôs Móveis Inteligentes', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Proces Dig de Sinais', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,4),
('Compiladores', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',60,40,4),
('Controle e Automação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,4),
('Gestão Ágil de Projetos', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,4),
('Inteligência Artificial', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',10,90,4),
('Sist Dist e Cloud Comp', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Economia para Engenharia', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4), 
('Segurança Cibernética', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4), 
('UX e Design Thinking', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Indústria 4.0', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Proj de Sis Emb', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Sistemas Tolerantes a Falhas', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),
('Tópc Espec em Tendências Tec', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,4),

-- GESTÃO DA TECNOLOGIA DA INFORMAÇÃO
('Inteligência de Negócios', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('Gestão Estratégica de TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('Gestão de Infra de TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('Gestão da Seg de Info', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),
('Gestão da Qualidade', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,3),

-- JOGOS DIGITAIS
('Desenho e Concept Art para Jog', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Design de Jogos I', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Empreendedorismo', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Intro à Progm para Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Intro aos Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Arte 2D para Jogos Digitais', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Amb de Desenv de Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Arte 3D para Jogos Digitais', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Design de Jogos II', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Progm para Jog Dig I', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5), 
('Proc de Prod de Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Game Level Design', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Design de Perso para Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Jog Digitais para Web', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Progm para Jogos Digitais II', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Roter e SB para Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Interf para Jogos Digitais', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Anima ÁU e VI para Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Estudos Comp em Jog Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Jog Dig para Disp Móveis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Mark para Jogos Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),
('Qualde e Test para Jogos Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,5),

-- PROCESSOS GERENCIAIS
('Modelos de Neg e Empree', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,2),
('Fundamentos de Sis Operc', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,2),
('Comp Org', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',70,30,2),
('Contabilidade Gerencial', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,2),

-- PRODUÇÃO MULTIMIDIA
('Teoria da Cor', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Filosofia', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Processo Criativo', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Storytelling', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Tipografia', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Comp Gráfica', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Fotografia Dig', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Gamificação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Novas Mídias', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Mark Dig e Mídias Soc', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('OPE3', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Criação e Prod Web', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Design de Info', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Direção de Arte', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Modelagem 3D', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Produção Audiovisual', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Semiótica', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Apk Mobile', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Cibercultura', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Ling Sonora', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('Efeitos Especiais', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),
('OPE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,6),

-- REDES DE COMPUTADORES
('Adm de Red e Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Arq. de Red de Comp', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Cabea Estruturado', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Progm para Redes', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Adm de Redes e Sis Operc. Liv', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Redes de Longa Distância', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Routing', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Seg em Redes e Infra.', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Gestão de TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Comunicação de Dados', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Diag. e Geren. de Redes', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Redes Convergentes', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Segurança em Sistemas', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Switching', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Computação em Nuvem', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Comunicações Móveis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Auditoria e Controle de TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Redes IPV6', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Serv. de Redes de Comp.', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),
('Tópicos Esp em Redes de Comp.', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,4),

-- SISTEMAS DE INFORMAÇÃO
('Business Agility', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Desv. de Sis. de Informação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Teoria da Computação', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Integração e Desv Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Business Intelligence', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Segurança e Auditoria de Sis', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Computação Cognitiva', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Governança de TI', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3),
('Gestão de projetos-EAD', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA','HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',90,10,3);

-- CONSULTA TABELA DISCIPLINA
SELECT * FROM DISCIPLINA


-- INSERINDO DADOS DE DISCIPLINA OFERTADA
-- DADOS DE SI (A, B) COORDENADOR TAKAI
INSERT INTO DISCIPLINAOFERTADA (IDCOORDENADOR, IDDISCIPLINA, IDCURSO, ANO, SEMESTRE, TURMA, IDPROFESSOR, METODOLOGIA, RECURSOS, CRITERIOAVALIACAO, PLANODEAULAS) VALUES
(3, 41, 11, 2018, 2, 'A', 24, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 42, 11, 2018, 2, 'A', 18, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 43, 11, 2018, 2, 'A',  3, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 44, 11, 2018, 2, 'A',  4, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 45, 11, 2018, 2, 'A', 36, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 46, 11, 2018, 2, 'A', 39, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 47, 11, 2018, 2, 'A', 40, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3,176, 11, 2018, 2, 'A', 17, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 41, 11, 2018, 2, 'B', 24, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 42, 11, 2018, 2, 'B', 18, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 43, 11, 2018, 2, 'B',  3, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 44, 11, 2018, 2, 'B',  4, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 45, 11, 2018, 2, 'B', 36, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 46, 11, 2018, 2, 'B', 39, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3, 47, 11, 2018, 2, 'B', 40, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(3,176, 11, 2018, 2, 'B', 17, 'PRESENCIAL', 'CLASSROOM', 'ACS + PROVA', 'PLANO');

-- DADOS DE ADS - EAD / COORDENADORA ANA CRISTINA DOS SANTOS
INSERT INTO DISCIPLINAOFERTADA (IDCOORDENADOR, IDDISCIPLINA, IDCURSO, ANO, SEMESTRE, TURMA, IDPROFESSOR, METODOLOGIA, RECURSOS, CRITERIOAVALIACAO, PLANODEAULAS) VALUES
(1, 41, 3, 2018, 2, 'A', 24, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 42, 3, 2018, 2, 'A', 18, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 43, 3, 2018, 2, 'A',  3, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 44, 3, 2018, 2, 'A',  4, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 45, 3, 2018, 2, 'A', 36, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 46, 3, 2018, 2, 'A', 39, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 47, 3, 2018, 2, 'A', 40, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1,176, 3, 2018, 2, 'A', 17, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO');

-- DADOS DE ADS / COORDENADORA ANA CRISTINA DOS SANTOS
INSERT INTO DISCIPLINAOFERTADA (IDCOORDENADOR, IDDISCIPLINA, IDCURSO, ANO, SEMESTRE, TURMA, IDPROFESSOR, METODOLOGIA, RECURSOS, CRITERIOAVALIACAO, PLANODEAULAS) VALUES
(1, 41, 2, 2018, 2, 'A', 24, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 42, 2, 2018, 2, 'A', 18, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 43, 2, 2018, 2, 'A',  3, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 44, 2, 2018, 2, 'A',  4, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 45, 2, 2018, 2, 'A', 36, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 46, 2, 2018, 2, 'A', 39, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 47, 2, 2018, 2, 'A', 40, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1,176, 2, 2018, 2, 'A', 17, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 41, 2, 2018, 2, 'B', 24, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 42, 2, 2018, 2, 'B', 18, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 43, 2, 2018, 2, 'B',  3, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 44, 2, 2018, 2, 'B',  4, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 45, 2, 2018, 2, 'B', 36, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 46, 2, 2018, 2, 'B', 39, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 47, 2, 2018, 2, 'B', 40, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1,176, 2, 2018, 2, 'B', 17, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 41, 2, 2018, 2, 'C', 24, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 42, 2, 2018, 2, 'C', 18, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 43, 2, 2018, 2, 'C',  3, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 44, 2, 2018, 2, 'C',  4, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 45, 2, 2018, 2, 'C', 36, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 46, 2, 2018, 2, 'C', 39, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 47, 2, 2018, 2, 'C', 40, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1,176, 2, 2018, 2, 'C', 17, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 41, 2, 2018, 2, 'D', 24, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 42, 2, 2018, 2, 'D', 18, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 43, 2, 2018, 2, 'D',  3, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 44, 2, 2018, 2, 'D',  4, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 45, 2, 2018, 2, 'D', 36, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 46, 2, 2018, 2, 'D', 39, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1, 47, 2, 2018, 2, 'D', 40, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO'),
(1,176, 2, 2018, 2, 'D', 17, 'EAD', 'CLASSROOM', 'ACS + PROVA', 'PLANO');

-- CONSULTANDO DISCIPLINAS OFERTADAS
SELECT * FROM DISCIPLINAOFERTADA

-- INSERINDO 40 SOLICITAÇÕES DE MATRICULAS
INSERT INTO SOLICITACAOMATRICULA(IDALUNO,IDDOFERTADA,IDCOORDENADOR,STATUS) VALUES
(1,1,1,'APROVADA'),
(1,2,1,'APROVADA'),
(2,1,1,'APROVADA'),
(2,2,1,'APROVADA'),
(3,1,1,'APROVADA'),
(3,2,1,'APROVADA'),
(4,1,1,'APROVADA'),
(4,2,1,'APROVADA'),
(5,1,1,'APROVADA'),
(5,2,1,'APROVADA'),

(1,3,1,'REJEITADA'),
(1,4,1,'REJEITADA'),
(2,3,1,'REJEITADA'),
(2,4,1,'REJEITADA'),
(3,3,1,'REJEITADA'),
(3,4,1,'REJEITADA'),
(4,3,1,'REJEITADA'),
(4,4,1,'REJEITADA'),
(5,3,1,'REJEITADA'),
(5,4,1,'REJEITADA'),  

(6,37,3,'SOLICITADA'),
(6,38,3,'SOLICITADA'),
(7,37,3,'SOLICITADA'),
(7,38,3,'SOLICITADA'),
(8,37,3,'SOLICITADA'),
(8,38,3,'SOLICITADA'),
(9,37,3,'SOLICITADA'),
(9,38,3,'SOLICITADA'),
(10,37,3,'SOLICITADA'),
(10,38,3,'SOLICITADA'),

(6,29,3,'CANCELADA'),
(6,30,3,'CANCELADA'),
(7,29,3,'CANCELADA'),
(7,30,3,'CANCELADA'),
(8,29,3,'CANCELADA'),
(8,30,3,'CANCELADA'),
(9,29,3,'CANCELADA'),
(9,30,3,'CANCELADA'),
(10,29,3,'CANCELADA'),
(10,30,3,'CANCELADA');


-- CONSULTANDO TABELA SOLICITACAO MATRICULA
SELECT * FROM SOLICITACAOMATRICULA


-- INSERINDO DADOS TABELA ATIVIDADE
INSERT INTO ATIVIDADE(TITULO, CONTEUDO, TIPO) VALUES
('AC1', 'REVISAO DO SEMESTRE PASSADO', 'TESTE'),
('AC2', 'CRIANDO UM BANCO DE DADOS', 'RESPOSTA ABERTA'),
('AC3', 'CRIANDO TABELAS NO BD', 'RESPOSTA ABERTA'),
('AC4', 'LISTA DE EXERCÍCIOS DDL', 'TESTE'),
('AC5', 'CRIANDO BD LMS', 'RESPOSTA ABERTA'),
('AC6', 'EXERCICIO DML(INSERT, UPDATE E DELETE)', 'RESPOSTA ABERTA'),
('AC7', 'EXERCICIO LMS(INSERINDO DADOS NAS TABELAS)', 'RESPOSTA ABERTA'),
('AC8', 'EXERCICIOS SUB-LINGUAGEM DML/DQL', 'RESPOSTA ABERTA'),
('AC9', 'REVISÃO DO CONTEÚDO DO SEMESTRE', 'TESTE'),
('AC10', 'REVISAO DO CONTEÚDO DO SEMESTRE', 'RESPOSTA ABERTA');


-- CONSULTA TABELA ATIVIDADE
SELECT * FROM ATIVIDADE


-- VINCULE 10 AC's PARA 2 DISCIPLINA OFERTADA/ 2 ENTREGAS PARA CADA ATIVIDADE VINCULADA
INSERT INTO ATIVIDADEVINCULADA (IDATIVIDADE, IDPROFESSOR, IDDOFERTADA, ROTULO, STATUS, DTINIRESPOSTA, DTFIMRESPOSTA) VALUES
(1,36,6,'TESTE SEUS CONHECIMENTOS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(2,36,6, 'CRIANDO UM BD', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(3,36,6, 'ALTERANDO E EXCLUINDO TABELAS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(4,36,6, 'LISTA DE EXERCÍCIOS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(5,36,6, 'CRIANDO BD-PROJETO LMS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(6,36,6, 'EXERCÍCIOS DML', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(7,36,6, 'PROJETO LMS - INSERT, UPDATE E DELETE', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(8,36,6, 'LMS-EXERCÍCIOS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(9,36,6, 'BANDO DE DADOS EX', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(10,36,6, 'EXERCÍCIOS EXTRAS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),

(1,3,5,'PRIMEIRA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(2,3,5,'SEGUNDA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(3,3,5,'TERCEIRA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(4,3,5,'QUARTA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(5,3,5,'QUINTA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(6,3,5,'SEXTA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(7,3,5,'SÉTIMA AC DE DEVOPS, UPDATE E DELETE', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(8,3,5,'OITAVA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(9,3,5,'NONA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 ),
(10,3,5,'DÉCIMA AC DE DEVOPS', 'DISPONIBILIZADA', GETDATE(), GETDATE()+30 );


-- CONSULTANDO TABELA ATIVIDADE VINCULADA
SELECT * FROM ATIVIDADEVINCULADA


-- 2 ENTREGAS PARA CADA ATIVIDADE VINCULADA (2X10X2=40)
INSERT INTO ENTREGA (IDALUNO, IDAVINCULADA, TITULO, RESPOSTA, STATUS, IDPROFESSOR, NOTA, DTAVALIACAO) VALUES
(1,1,'ENREGA AC1', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 10, GETDATE()),
(1,2,'ENTREGA AC2', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 9, GETDATE()),
(1,3,'ENTREGA AC3', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 9, GETDATE()),
(1,4,'ENTREGA AC4', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 10, GETDATE()),
(1,5,'ENTREGA AC5', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 8, GETDATE()),
(2,1,'ENTREGA AC1', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 9, GETDATE()),
(2,2,'ENTREGA AC2', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 7, GETDATE()),
(2,3,'ENTREGA AC3', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 9, GETDATE()),
(2,4,'ENTREGA AC4', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 6, GETDATE()),
(2,5,'ENTREGA AC5', '1-A, 2-B, 3-C', 'CORRIGIDO', 18, 8, GETDATE()),

(1,11,'ENREGA AC1', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 10, GETDATE()),
(1,12,'ENTREGA AC2', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 9, GETDATE()),
(1,13,'ENTREGA AC3', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 6, GETDATE()),
(1,14,'ENTREGA AC4', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 10, GETDATE()),
(1,15,'ENTREGA AC5', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 8, GETDATE()),
(2,11,'ENTREGA AC1', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 9, GETDATE()),
(2,12,'ENTREGA AC2', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 7, GETDATE()),
(2,13,'ENTREGA AC3', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 9, GETDATE()),
(2,14,'ENTREGA AC4', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 7, GETDATE()),
(2,15,'ENTREGA AC5', '1-A, 2-B, 3-C', 'CORRIGIDO', 36, 8, GETDATE());

INSERT INTO ENTREGA (IDALUNO, IDAVINCULADA, TITULO, RESPOSTA, STATUS) VALUES
(1,6,'ENREGA AC6', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,7,'ENTREGA AC7', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,8,'ENTREGA AC8', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,9,'ENTREGA AC9', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,10,'ENTREGA AC10', '1-A, 2-B, 3-C','ENTREGUE'),
(2,6,'ENTREGA AC6', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,7,'ENTREGA AC7', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,8,'ENTREGA AC8', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,9,'ENTREGA AC9', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,10,'ENTREGA AC10', '1-A, 2-B, 3-C', 'ENTREGUE'),

(1,16,'ENREGA AC6', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,17,'ENTREGA AC7', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,18,'ENTREGA AC8', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,19,'ENTREGA AC9', '1-A, 2-B, 3-C', 'ENTREGUE'),
(1,20,'ENTREGA AC10', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,16,'ENTREGA AC6', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,17,'ENTREGA AC7', '1-A, 2-B, 3-C', 'ENTREGUE'),
(2,18,'ENTREGA AC8', '1-A, 2-B, 3-C1', 'ENTREGUE'),
(2,19,'ENTREGA AC9', '1-A, 2-B, 3-C1', 'ENTREGUE'),
(2,20,'ENTREGA AC10', '1-A, 2-B, 3-C1', 'ENTREGUE');


-- CONSULTA TABELA ENTREGA
SELECT * FROM ENTREGA


-- INSERINDO 30 MENSAGEM FICTÍCIAS ENTRE ALUNO E PROFESSOR
INSERT INTO MENSAGEM (IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO, DTRESPOSTA, RESPOSTA) VALUES
(1, 18,'LINGUAGEM SQL', 'FALTA', 'PROFESSOR FAVOR VERIFICAR MINHA FALTA DO DIA 10/07', 'RESPONDIDO', '20180712','20180715','FALTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(2, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/05', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(3, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 25/05', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(4, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 13/05', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(5, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 27/09', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(6, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 26/05', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(7, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 16/05', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(8, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 04/07', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(9, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/06', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR'),
(10, 18,'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/07', 'RESPONDIDO', '20180712', '20180715', 'NOTA LANÇADA ERRONEAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR');

INSERT INTO MENSAGEM (IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO) VALUES
(11, 18, 'LINGUAGEM SQL', 'FALTA', 'PROFESSOR FAVOR VERIFICAR MINHA FALTA DO DIA 10/07', 'LIDO', '20180712'),
(12, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/05', 'LIDO', '20180712'),
(13, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 25/05', 'LIDO', '20180712'),
(14, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 13/05', 'LIDO', '20180712'),
(15, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 27/09', 'LIDO', '20180712'),
(16, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 26/05', 'LIDO', '20180712'),
(17, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 16/05', 'LIDO', '20180712'),
(18, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 04/07', 'LIDO', '20180712'),
(19, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/06', 'LIDO', '20180712'),
(20, 28, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/07', 'LIDO', '20180712');


INSERT INTO MENSAGEM (IDALUNO, IDPROFESSOR, ASSUNTO, REFERENCIA, CONTEUDO, STATUS, DTENVIO) VALUES
(21, 18, 'LINGUAGEM SQL', 'FALTA', 'PROFESSOR FAVOR VERIFICAR MINHA FALTA DO DIA 10/07', 'ENVIADO', '20180712'),
(22, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/05', 'ENVIADO', '20180712'),
(23, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 25/05', 'ENVIADO', '20180712'),
(24, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 13/05', 'ENVIADO', '20180712'),
(25, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 27/09', 'ENVIADO', '20180712'),
(26, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 26/05', 'ENVIADO', '20180712'),
(27, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 16/05', 'ENVIADO', '20180712'),
(28, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 04/07', 'ENVIADO', '20180712'),
(29, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/06', 'ENVIADO', '20180712'),
(30, 18, 'LINGUAGEM SQL', 'NOTA', 'PROFESSOR ESTOU SEM A NOTA DO DIA 10/07', 'ENVIADO', '20180712');


-- CONSULTANDO TABELA MENSAGEM
SELECT * FROM MENSAGEM


--EXCLUINDO PROFESSOR QUE NÃO TEM NENHUMA RELAÇÃO COM OS DADOS DE OUTRA TABELA (UTILIZE DELETE)
DELETE PROFESSOR WHERE ID = 20

-- CONSULTANDO A TABELA PROFESSOR 
SELECT * FROM PROFESSOR

--EXCLUA UM ALUNO QUE NÃO TENHA NENHUMA RELAÇÃO COM DADOS DE OUTRA TABELA (UTILIZE DELETE)
DELETE ALUNO WHERE ID = 44

-- CONSULTANDO A TABELA ALUNO
SELECT * FROM ALUNO

--ALTERE A SENHA DO PROFESSOR GUSTAVO MENDES FERREIRA (UTILIZE UPDATE)
UPDATE USUARIO SET SENHA = 'GF654321' WHERE ID =68

-- CONSULTANDO A TABELA USUÁRIO
SELECT * FROM USUARIO

-- ALTERE UMA MENSAGEM QUE ESTAVA COM STATUS 'LIDO' PARA RESPONDIDO. LEMBRE-SE QUE SERÁ NECESSÁRIO CADASTRAR A DATA DA RESPOSTA E A REPOSTA (UTILIZE UPDATE)
UPDATE MENSAGEM SET STATUS = 'RESPONDIDO', DTRESPOSTA=GETDATE(),RESPOSTA='NOTA LANÇADA ERRONAMENTE, JÁ AJUSTADO. FAVOR VERIFICAR' WHERE STATUS='LIDO';

-- CONSULTANDO A TABELA MENSAGEM
SELECT * FROM MENSAGEM

-- ALTERE UMA ENTREGA QUE ESTAVA COM STATUS 'ENTREGUE' PARA 'CORRIGIDO". LEMBRE-SE QUE SERÁ NECESSÁRIO ATUALIZAR O IDPROFESSOR, A NOTA E A DATA DA AVALIAÇÃO, ALÉM DA TROCA DO STATUS (UTILIZE UPDATE)
UPDATE  ENTREGA SET STATUS = 'CORRIGIDO', IDPROFESSOR = 4, NOTA = 10, DTAVALIACAO = GETDATE() WHERE STATUS = 'ENTREGUE';

-- CONSULTANDO A TABELA ENTREGA
SELECT * FROM ENTREGA